### ISSUE TITLE
Witam

### ISSUE THREAD

**Issue by maciejciukaj** [31grudnia/zad1-chmury#1]
Witam, na platformie github. Proszę wstawić swoje zdjęcie żebym mógł Pana łatwo poznać w firmie. Żegnam

**Comment by 31grudnia** [comment]
Witam serdecznie na moim typowo typowym repo, pozdrawiam. Niżej moje aktualne zdjęcie...
<img width="117" alt="George_Floyd" src="https://user-images.githubusercontent.com/83308784/167018495-4ae757cc-b8e6-47be-98d4-91c1e0cffac8.png">

**Comment by maciejciukaj** [comment]
to na pewno nie jest Pan, proszę nie robić sobie żartów
